import "./globals.css";
import { LangProvider } from '../components/LanguageContext'
import Header from '../components/Header'
import Footer from '../components/Footer'

export const metadata = {
  title: "Apollo Creations",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LangProvider>
          <Header />
          {children}
          <Footer />
        </LangProvider>
      </body>
    </html>
  )
}